version: 2
jobs:
  shared:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run:
          name: KTLint
          command: ./gradlew ktlintCheck
      - run:
          name: Assemble & Test Shared Framework
          command: ./gradlew testRelease
  ios:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - restore_cache:
          key: "v2-gems"
      - run:
          name: Install with bundler
          command: bundle check || bundle install --path .bundle
      - save_cache:
          key: "v2-gems"
          paths: ["./.bundle"]
      - run:
          name: Run All Tests
          command: bundle exec fastlane ios ci_test
  android:
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run:
          name: KTLint
          command: ./gradlew ktlintCheck
      - run:
          name: Assemble & Test
          command: ./gradlew testRelease

workflows:
  version: 2
  build_and_test:
    jobs:
      - shared
      - ios
      - android
