excluded:
  - Pods
  - .bundle
  - Scripts
disabled_rules:
  - file_length
  - function_body_length
  - function_parameter_count
  - trailing_comma
  - type_body_length
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - unused_private_declaration
trailing_whitespace:
  ignores_empty_lines: true
cyclomatic_complexity:
  ignores_case_statements: true
identifier_name:
  min_length:
    warning: 1
  allowed_symbols:
    - _
type_name:
  min_length:
    warning: 1
  allowed_symbols:
    - _
line_length:
  warning: 150
  error: 9999
private_outlet:
  allow_private_set: true
