platform :ios, '12.0'

target 'DoorbellBotNative' do
  pod 'SwiftLint', '~>0.27.0'

  target 'DoorbellBotNativeTests' do
    inherit! :search_paths
  end

  target 'DoorbellBotNativeUITests' do
    inherit! :search_paths
    pod 'EarlGrey', '~>1.15.0'
  end
end
