platform :ios, '12.0'

use_frameworks!

target 'DoorbellBotNative' do
  pod 'SwiftLint', '~>0.27.0'
  pod 'Firebase/Core', '~>5.12.0'
  pod 'Fabric', '~> 1.8.2'
  pod 'Crashlytics', '~> 3.11.1'

  target 'DoorbellBotNativeTests' do
    inherit! :search_paths
  end

  target 'DoorbellBotNativeUITests' do
    inherit! :search_paths
    pod 'EarlGrey', '~>1.15.0'
  end
end
